name: Create release

# Adapted from: https://dev.to/ayoub3bidi/quick-tutorial-how-to-add-a-release-github-workflow-56ib

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  all-release:
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository @ Tag
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run cross-compile script
        run: ./build.sh github.com/sanelson/gopim all

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag}" \
              --generate-notes \
              gopim-linux-amd64 \
              gopim-windows-386.exe \
              gopim-windows-amd64.exe

  osx-release:
    needs: all-release
    name: Release OSX binary
    runs-on: macos-latest
    steps:
      - name: Checkout repository @ Tag
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run native OSX build
        run: ./build.sh github.com/sanelson/gopim darwin/amd64

      - name: Upload OSX binary to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release upload "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              gopim-darwin-amd64

